name: FTP Upload Test
on:
  push:
    branches:
      - main
jobs:
  upload-ftp:
    name: Upload using FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload
        uses: ./
        with:
          host: ${{ secrets.INFINITYFREE_FTP_HOST }}
          username: ${{ secrets.INFINITYFREE_FTP_USERNAME }}
          password: ${{ secrets.INFINITYFREE_FTP_PASSWORD }}
          paths: |
            files /files
            index.html /htdocs
